name: Build Java JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v2

    - name: Step 2 - Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Step 3 - Build JAR using Maven
      run: mvn -B package --file pom.xml

    - name: Step 4 - Show directory overview
      run: |
        ls -la
        cd target
        ls -la

    - name: Step 5 - Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: WASP
        path: target/*.jar
